# Generated by Django 5.1.4 on 2025-01-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
    ]
