# Generated by Django 5.1.4 on 2025-03-06 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='chapter_contents/')),
                ('title_class_sub_chapter_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_contents', to='educational.titleclasssubchaptercategory')),
            ],
        ),
        migrations.AddField(
            model_name='categoryquestion',
            name='chapter_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='educational.chaptercontent'),
        ),
        migrations.CreateModel(
            name='FillInTheBlanks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('title_class_sub_chapter_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fill_in_the_blanks', to='educational.titleclasssubchaptercategory')),
            ],
        ),
        migrations.AddField(
            model_name='categoryquestion',
            name='fill_in_the_blanks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='educational.fillintheblanks'),
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('title_class_sub_chapter_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='educational.titleclasssubchaptercategory')),
            ],
        ),
        migrations.AddField(
            model_name='categoryquestion',
            name='notes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='educational.notes'),
        ),
        migrations.CreateModel(
            name='TrueOrFalse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('is_true', models.BooleanField()),
                ('title_class_sub_chapter_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='true_or_false', to='educational.titleclasssubchaptercategory')),
            ],
        ),
        migrations.AddField(
            model_name='categoryquestion',
            name='true_or_false',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='educational.trueorfalse'),
        ),
    ]
