# Generated by Django 5.1.4 on 2025-03-04 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classname',
            name='heading',
        ),
        migrations.CreateModel(
            name='ClassHeading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_headings', to='educational.classname')),
                ('heading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_headings', to='educational.heading')),
            ],
            options={
                'unique_together': {('class_name', 'heading')},
            },
        ),
    ]
