# Generated by Django 5.1.4 on 2025-03-04 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0003_chapter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='subject',
        ),
        migrations.CreateModel(
            name='ClassSubjectChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subject_chapters', to='educational.chapter')),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subject_chapters', to='educational.classname')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subject_chapters', to='educational.subject')),
            ],
            options={
                'unique_together': {('class_name', 'subject', 'chapter')},
            },
        ),
    ]
