# Generated by Django 5.1.4 on 2025-04-08 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0003_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='titleclasssubject',
            name='image',
            field=models.ImageField(blank=True, default='default_images/default.jpg', upload_to='title_class_subject_images/'),
        ),
    ]
