# Generated by Django 5.1.4 on 2025-04-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0004_titleclasssubject_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titleclasssubject',
            name='image',
            field=models.ImageField(blank=True, default='educational/images/default.jpg', upload_to='title_class_subject_images/'),
        ),
    ]
