# Generated by Django 5.1.4 on 2025-03-05 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0005_contentcategory_alter_chapter_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='educational.subject'),
            preserve_default=False,
        ),
    ]
