# Generated by Django 5.1.4 on 2025-03-05 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0007_detailedanswer_mcq_shortanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=50)),
                ('content_id', models.PositiveIntegerField()),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_links', to='educational.chapter')),
                ('content_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_links', to='educational.contentcategory')),
            ],
        ),
    ]
