# Generated by Django 5.2 on 2025-04-09 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0007_alter_titleclasssubject_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('fill_in_the_blanks', models.ManyToManyField(related_name='tests', to='educational.fillintheblanks')),
                ('mcqs', models.ManyToManyField(related_name='tests', to='educational.mcq')),
                ('title_class_sub_chapter_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='educational.titleclasssubchaptercategory')),
                ('true_or_false', models.ManyToManyField(related_name='tests', to='educational.trueorfalse')),
            ],
        ),
    ]
