# Generated by Django 5.2 on 2025-04-09 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0008_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
